package entidades;
// Generated 23/06/2019 06:32:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Clientes generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String apellido;
     private Date fechadeNacimiento;
     private String direccion;
     private String numeroTelefono;
     private String e_mail;

    public Cliente() {
    }

    public Cliente(int idCliente, String nombre, String apellido, Date fechadeNacimiento, String direccion, String numeroTelefono, String e_mail) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechadeNacimiento = fechadeNacimiento;
       this.direccion = direccion;
       this.numeroTelefono = numeroTelefono;
       this.e_mail = e_mail;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNaci() {
        return this.fechadeNacimiento;
    }
    
    public void setfechadeNacimiento(Date fechadeNacimiento) {
        this.fechadeNacimiento = fechadeNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getnumeroTelefono() {
        return this.numeroTelefono;
    }
    
    public void setnumeroTelefono(String numeroTelefono) {
        this.numeroTelefono = numeroTelefono;
    }
    public String getE_mail() {
        return this.e_mail;
    }
    
    public void setE_mail(String email) {
        this.e_mail = e_mail;
    }




}


